sudo: required
dist: trusty
language: go
go:
  - 1.13.x
script:
  - |
    if [ "${TRAVIS_BRANCH}" == "px-rel-1.4" ]; then
      export DOCKER_HUB_STORAGE_OPERATOR_TAG=1.4.0-dev
      export BUILD_VER="${TRAVIS_BUILD_NUMBER}"
    else
      export DOCKER_HUB_STORAGE_OPERATOR_TAG=`git rev-parse --short HEAD`
    fi
    make && make downloads && make test && make verify-catalog && make container &&
    if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}";
      make deploy;
      if [ "${TRAVIS_BRANCH}" == "px-rel-1.4" ]; then
        make deploy-catalog
      fi
    fi
notifications:
  email:
    on_success: always
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash)
